### ISSUE TITLE
Add constraint

### ISSUE THREAD

**Issue by mykahveli** [samirsaci/workforce-planning#1]
Hello Samir,

I changed it to two shifts but i'm having a shift with zero workers. How can I add a constraint in order to have at least 1 in each shifts?

![image](https://github.com/samirsaci/workforce-planning/assets/19893245/417b75ae-6b36-4740-b62d-a4c4ee528c80)

Thank you in advance.

**Comment by samirsaci** [comment]
This is normal, I also have the results.

It's not that you have zero workers in this shift. You just did not hire a new worker during this shift.

The workers already in the loop were enough to meet the demand.

Got it?
